# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets


class MainWindowUI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1031, 653)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 301, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.p1_pts = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.p1_pts.setFont(font)
        self.p1_pts.setObjectName("p1_pts")
        self.verticalLayout.addWidget(self.p1_pts)
        self.p2_pts = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.p2_pts.setFont(font)
        self.p2_pts.setObjectName("p2_pts")
        self.verticalLayout.addWidget(self.p2_pts)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 110, 1011, 531))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.img14 = QtWidgets.QWidget(self.widget)
        self.img14.setObjectName("img14")
        self.gridLayout.addWidget(self.img14, 2, 1, 1, 1)
        self.img11 = QtWidgets.QWidget(self.widget)
        self.img11.setObjectName("img11")
        self.gridLayout.addWidget(self.img11, 1, 4, 1, 1)
        self.img8 = QtWidgets.QWidget(self.widget)
        self.img8.setObjectName("img8")
        self.gridLayout.addWidget(self.img8, 1, 1, 1, 1)
        self.img9 = QtWidgets.QWidget(self.widget)
        self.img9.setObjectName("img9")
        self.gridLayout.addWidget(self.img9, 1, 2, 1, 1)
        self.img1 = QtWidgets.QWidget(self.widget)
        self.img1.setObjectName("img1")
        self.gridLayout.addWidget(self.img1, 0, 0, 1, 1)
        self.img13 = QtWidgets.QWidget(self.widget)
        self.img13.setObjectName("img13")
        self.gridLayout.addWidget(self.img13, 2, 0, 1, 1)
        self.img19 = QtWidgets.QWidget(self.widget)
        self.img19.setObjectName("img19")
        self.gridLayout.addWidget(self.img19, 3, 0, 1, 1)
        self.img3 = QtWidgets.QWidget(self.widget)
        self.img3.setObjectName("img3")
        self.gridLayout.addWidget(self.img3, 0, 2, 1, 1)
        self.img6 = QtWidgets.QWidget(self.widget)
        self.img6.setObjectName("img6")
        self.gridLayout.addWidget(self.img6, 0, 5, 1, 1)
        self.img10 = QtWidgets.QWidget(self.widget)
        self.img10.setObjectName("img10")
        self.gridLayout.addWidget(self.img10, 1, 3, 1, 1)
        self.img7 = QtWidgets.QWidget(self.widget)
        self.img7.setObjectName("img7")
        self.gridLayout.addWidget(self.img7, 1, 0, 1, 1)
        self.img2 = QtWidgets.QWidget(self.widget)
        self.img2.setObjectName("img2")
        self.gridLayout.addWidget(self.img2, 0, 1, 1, 1)
        self.img21 = QtWidgets.QWidget(self.widget)
        self.img21.setObjectName("img21")
        self.gridLayout.addWidget(self.img21, 3, 2, 1, 1)
        self.img20 = QtWidgets.QWidget(self.widget)
        self.img20.setObjectName("img20")
        self.gridLayout.addWidget(self.img20, 3, 1, 1, 1)
        self.img22 = QtWidgets.QWidget(self.widget)
        self.img22.setObjectName("img22")
        self.gridLayout.addWidget(self.img22, 3, 3, 1, 1)
        self.img12 = QtWidgets.QWidget(self.widget)
        self.img12.setObjectName("img12")
        self.gridLayout.addWidget(self.img12, 1, 5, 1, 1)
        self.img16 = QtWidgets.QWidget(self.widget)
        self.img16.setObjectName("img16")
        self.gridLayout.addWidget(self.img16, 2, 3, 1, 1)
        self.img23 = QtWidgets.QWidget(self.widget)
        self.img23.setObjectName("img23")
        self.gridLayout.addWidget(self.img23, 3, 4, 1, 1)
        self.img5 = QtWidgets.QWidget(self.widget)
        self.img5.setObjectName("img5")
        self.gridLayout.addWidget(self.img5, 0, 4, 1, 1)
        self.img17 = QtWidgets.QWidget(self.widget)
        self.img17.setObjectName("img17")
        self.gridLayout.addWidget(self.img17, 2, 4, 1, 1)
        self.img18 = QtWidgets.QWidget(self.widget)
        self.img18.setObjectName("img18")
        self.gridLayout.addWidget(self.img18, 2, 5, 1, 1)
        self.img4 = QtWidgets.QWidget(self.widget)
        self.img4.setObjectName("img4")
        self.gridLayout.addWidget(self.img4, 0, 3, 1, 1)
        self.img24 = QtWidgets.QWidget(self.widget)
        self.img24.setObjectName("img24")
        self.gridLayout.addWidget(self.img24, 3, 5, 1, 1)
        self.img15 = QtWidgets.QWidget(self.widget)
        self.img15.setObjectName("img15")
        self.gridLayout.addWidget(self.img15, 2, 2, 1, 1)
        self.img25 = QtWidgets.QWidget(self.widget)
        self.img25.setObjectName("img25")
        self.gridLayout.addWidget(self.img25, 4, 0, 1, 1)
        self.img26 = QtWidgets.QWidget(self.widget)
        self.img26.setObjectName("img26")
        self.gridLayout.addWidget(self.img26, 4, 1, 1, 1)
        self.img27 = QtWidgets.QWidget(self.widget)
        self.img27.setObjectName("img27")
        self.gridLayout.addWidget(self.img27, 4, 2, 1, 1)
        self.img28 = QtWidgets.QWidget(self.widget)
        self.img28.setObjectName("img28")
        self.gridLayout.addWidget(self.img28, 4, 3, 1, 1)
        self.img29 = QtWidgets.QWidget(self.widget)
        self.img29.setObjectName("img29")
        self.gridLayout.addWidget(self.img29, 4, 4, 1, 1)
        self.img30 = QtWidgets.QWidget(self.widget)
        self.img30.setObjectName("img30")
        self.gridLayout.addWidget(self.img30, 4, 5, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Memory Game"))
